export const SET_USER_API_LOADING = 'SET_USER_API_LOADING'


export const EMAIL_CODE_SUCCESS = 'EMAIL_CODE_SUCCESS'
export const EMAIL_CODE_FAIL = 'EMAIL_CODE_FAIL'


export const MOBILE_CODE_SUCCESS = 'MOBILE_CODE_SUCCESS'
export const MOBILE_CODE_FAIL = 'MOBILE_CODE_FAIL'
export const RESET_USER_STATE = 'RESET_USER_STATE'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'