export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'

export const REFF_SUCCESS = 'REFF_SUCCESS'
export const REFF_FAIL = 'REFF_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'


export const CREATE_PASSCODE_SUCCESS = 'CREATE_PASSCODE_SUCCESS'
export const CREATE_PASSCODE_FAIL = 'CREATE_PASSCODE_FAIL'

export const CREATE_EMAIL_SUCCESS = 'CREATE_EMAIL_SUCCESS'

export const CREATE_PHONE_SUCCESS = 'CREATE_PHONE_SUCCESS'


export const AUTH_ERROR = 'AUTH_ERROR'


